---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ProjectName:
    Type: String
  Bucket:
    Type: String
    Default: a2c-qs-assets
  BucketKey:
    Type: String
    Default: ast-jjen/functions/packages/ConfigParser/lambda.zip
  MainStackParams:
    Type: String
    Default: s3%3A%2F%2Fjjen-configurator-test%2Fmy_params.json
  MainStackTemplateUrl:
    Type: String

Resources:
  ConfigParserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: jjen-test-CustomResourceRole
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Path: /am-a2c/
      PermissionsBoundary: arn:aws-us-gov:iam::016915823617:policy/Security_Boundary_NoIAM      
      Policies:
        - PolicyDocument:
            Statement:
              - Action: iam:GetRole
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: role-checker
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "*"
  ConfigParser:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-ConfigParser
      Handler: config_parser.handler
      MemorySize: 256
      Timeout: 300
      Role: !GetAtt ConfigParserRole.Arn
      Runtime: python3.9
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Ref BucketKey

  Config:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt ConfigParser.Arn
      MainStackParams: !Ref MainStackParams

  MainStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref MainStackTemplateUrl
      Parameters:
        Foo: Bar
